version: '3.5'

services:

  aai_web:
    image: bref/php-81-fpm-dev:2
    ports:
      - 8888:8000
    volumes:
        - .:/var/task
    environment:
        HANDLER: web/index.php
        DOCUMENT_ROOT: web

  aai_vite:
    image: node:20.2
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn && yarn dev"
